### ISSUE TITLE
Different licenses for repo and website

### ISSUE THREAD

**Issue by MoinJulian** [cojocaru-david/cojocarudavid.me#1]
Hi,
I’m a bit confused, your repository is licensed under MIT but on your website you wrote All Rights Reserved, so which applies?
I would like to contribute if possible.

Kind regards
Julian Hammer

**Comment by cojocaru-david** [comment]
Hi Julian,

Thank you for bringing this to my attention, and I appreciate your willingness to contribute! Apologies for the confusion regarding the licensing information. It seems there was an oversight, and the correct license is indeed MIT.

Feel free to proceed with your contribution, and if you have any further questions or encounter issues, please don't hesitate to contact me.

Best regards,
Cojocaru David
